# Generated by Django 4.2 on 2023-06-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mijoz',
            name='qarz',
            field=models.CharField(default=0, max_length=70),
        ),
    ]
